$INCLUDE(DELAYS.ASM)
$INCLUDE(SEG1.ASM)
SW1 BIT P3^0
SW2 BIT P3^1
CSEG AT 0
MAIN:
	MOV DPTR,#SEG_LUT
	MOV R4,#00
AGAIN:
	ACALL DISP_2_MUX_SEG
      	JNB SW2,AGAIN2
	JB SW1,AGAIN
	INC R4
	ACALL DELAY1MS
	ACALL DISP_2_MUX_SEG

        JNB SW1,$
	CJNE R4,#60,AGAIN
	SJMP MAIN
AGAIN2:	JNB SW2,$
	
AGAIN3:	
	MOV R3,#255
	AGAIN4:
		ACALL DISP_2_MUX_SEG
		DJNZ R3,AGAIN4
	DJNZ R4,AGAIN3
	SJMP MAIN
END
