a.out : add1.o print.o menu.o delete.o save.o getdata.o
	cc -o a.out add1.o print.o menu.o delete.o save.o getdata.o
add1.o : add1.c
print.o : print.c
menu.o : menu.c
delete.o : delete.c
save.o : save.c
getdata.o : getdata.c
